### ISSUE TITLE
Add New Relic to eregs

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-eregs#312]
As part of our ATO we need to add New Relic to eRegs.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-eregs/pull/317

**Comment by tadhg-ohiggins** [comment]
Reopening because I still don't see any reference to this on the New Relic dashboard.

**Comment by ccostino** [comment]
I wonder if we need to manually add it in New Relic itself, too?  I can't tell from their docs.

**Comment by noahmanger** [comment]
This has been resolved.
